[package]
name = "core"
version = "0.1.0"
edition = "2021"

repository = "https://gitee.com/conero/pinyin-shared"
description = "基于 rust 编写 汉字拼音相关处理"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
path = "lib.rs"

[dependencies]
