[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "lib.rs"
# 生成 dll 文件
crate-type = ["cdylib"]
name = "pinyin"

[dependencies]
